---
#This playbook installs Apache
- name: Set up server
  hosts: linuxacademyservers
  tasks: 
    - name: Install Apache Packages
      yum:
        name: httpd
        state: present
    - name: Run Apache
      service: 
        name: httpd 
        state: started